### ISSUE TITLE
Highlight past and new hackathon entries

### ISSUE THREAD

**Issue by epowell101** [OpenDataforWeb3/Resources#106]
We discussed:
1.  Creating a new repository and possibly a new organization into which we can fork ALL of the prior and new entrants;
    - this can be branded as our Sandbox 
2.  Creating a ReadMe - that is an index for all hackathon entries
3.  Connecting the Hackathon navigation to a new page that also lists all the hackathon entries
4.  Putting this list also in Official Links and elsewhere

**Comment by epowell101** [comment]
Is this roughly what we discussed @poupou-web3 @sarob ?

**Comment by sarob** [comment]
Updated the PR #111 to include the different hackathon references to repoint to the new ODC Jan2023 Hackathon repository.

**Comment by epowell101** [comment]
Closing because also did the Gitcoin post to highlight them
