### ISSUE TITLE
governance structure for community

### ISSUE THREAD

**Issue by epowell101** [OpenDataforWeb3/Resources#11]
Initial thoughts are under development

The basic idea would be to have technical decisions insulated from any pressures
And to use quadratic voting as well

Everything that can be on chain - should be.  We can also constrain the surface area for capture via written guidelines.

**Comment by sarob** [comment]
I would start with debating a few of the questions posed in the ODC slidedeck. 
- How much be like CNCF? Holding in person marketplace events is big for COSS marketing and fundraising. Plus getting most of the project contributors f2f.
- What are the assets? For many COSS it's the brand trademark. 
- Will there be a non-profit foundation for liability, tax, and legal protections? The legal experts need to answer for today and what's likely over the next few years. 
- technical responsibilities derived from the projects and community? I have experience with 100% community technical responsibility. There is a good case for an employee of the organization to have product responsibilities and act as a tie breaker when the community gets deadlocked.

**Comment by sarob** [comment]
How and when to vote, establishing policy, documenting the results is important. Need to figure out the above questions first.

**Comment by sarob** [comment]
I have started the governance basics by creating a contributing file #37 . We are discussing in the devrel thread. 

@epowell101 We need to establish a license and code of conduct soon. 

The more strategic stuff I commented on above can wait for a bit.

**Comment by sarob** [comment]
From @epowell101 : This overview of recent experiments in DAO governance - including dual house structures similar to that we’ve envisioned - was published a couple of weeks ago and seems useful:  https://linda.mirror.xyz/kZHqJdvMD6OWk8-c3SF-oBJFFX_JrAPkhhB8iJKNM60

**Posted from msg https://discord.com/channels/1037443230993743902/1038206685224902658/1057024154840350820**

**Comment by sarob** [comment]
We should close this as we finalize what to do with sandbox projects

**Comment by epowell101** [comment]
suggest we break this into discrete parts:
- Regen Rangers etc
- Sandbox
- Overall governance including for new founding partners
