### ISSUE TITLE
Turn up a governance / community forum

### ISSUE THREAD

**Issue by epowell101** [OpenDataforWeb3/Resources#12]
Set up the governance forum

**Comment by epowell101** [comment]
Most projects use the same Forum software and service.

Examples:
- Gitcoin:  https://gov.gitcoin.co/
- `https://community.supermodular.xyz/`

The purpose is to have this set up for a near term future when the forum will be used for proposals and so forth

**Comment by MAWUT0R** [comment]
hello @epowell101, I would love to take this up, and I believe the examples of the governance forums above use [Discourse](https://www.discourse.org/), please check it out and let me know what you think.

**Comment by owanikin** [comment]
Hi @epowell101 I'm currently doing some deep research (though may not be needed for this work) on on-chain governance. I will love to take this one if it is available.

**Comment by sarob** [comment]
I think could be a great multi contributor file and discord collaboration. Governance is a cool topic and automation of it is a evergreen DAO topic. 

@epowell101 mentioned creating some groups of topics for tools and governance discussions. Maybe we start there in a gov doc with a PR. And start discussing in PR and discord.

**Comment by epowell101** [comment]
I'm specifically talking about setting up the Forum software / service used by each of those Forums. 

If you look around at the Forums used for submitting proposals across the web3 ecosystem they are all the same.  This task is to determine what that is, set up a basic version w/ some categories for OpenData Community

**Comment by owanikin** [comment]
Hey @sarob @epowell101 , what's the next step on this? 

- To set up this governance/forum software?
- What are some categories for the OpenData community: Should the categories be split along bounty lines?

**Comment by sarob** [comment]
There are few tools: govrn and gardens among them. Maybe we can focus on this as the hackathon work is behind us. Sean ***@***.*** On Jan 30, 2023, at 06:33, Owanikin ***@***.***> wrote:﻿
Hey @sarob @epowell101 , what's the next step on this?

To set up this governance/forum software?
What are some categories for the OpenData community: Should the categories be split along bounty lines?

**Comment by sarob** [comment]
We talked a bit more about governance today in the ODC meeting. We need to get sponsor feedback to make a plan for what’s next. We will explore tooling to enable the plan shortly after.  Sean ***@***.*** On Jan 30, 2023, at 15:44, Sean Roberts ***@***.***> wrote:﻿There are few tools: govrn and gardens among them. Maybe we can focus on this as the hackathon work is behind us. Sean ***@***.*** On Jan 30, 2023, at 06:33, Owanikin ***@***.***> wrote:﻿
Hey @sarob @epowell101 , what's the next step on this?

To set up this governance/forum software?
What are some categories for the OpenData community: Should the categories be split along bounty lines?

**Comment by krrsna37** [comment]
In the Open Data Community, data sets can be organized and classified into different categories based on their nature, structure, and use cases. Here are some common categories:
  Geospatial Data: This refers to data that has a geographic or spatial component, such as maps, satellite imagery, and location data.
 Statistical Data: This refers to data that provides information on statistics, such as demographic data, economic indicators, and other data related to population, industry, and more.
  Financial Data: This refers to data that provides information on financial markets, such as stock prices, currency exchange rates, and other data related to the economy.
  Environmental Data: This refers to data that provides information on the environment, such as weather data, air quality data, and other data related to the earth's systems and processes.
  Healthcare Data: This refers to data that provides information on health and medical research, such as patient data, drug trials, and other data related to healthcare and medicine.
   Social Data: This refers to data that provides information on social issues and trends, such as social media data, survey data, and other data related to human behaviour and social structures.

**Comment by epowell101** [comment]
Closing this I set up the basic Discourse.  We can open another one focused on government and pipelines
