### ISSUE TITLE
Logo design for ODC #9

### ISSUE THREAD

**Issue by krrsna37** [OpenDataforWeb3/Resources#120]
#9 
simple logo design for ODC
1)
![ODClogo](https://user-images.githubusercontent.com/81230749/217322764-8ab290ea-73d6-459d-8345-8add3072c42d.jpeg)

2)
![ODClogo2](https://user-images.githubusercontent.com/81230749/217322906-e076b8b0-8bb6-41a3-aa31-596c6fa852d3.jpeg)

**Comment by Razga** [comment]
They look very cool. In the past I would have chosen the first one, but seeing how Gitcoin is growing lichenpunk, I'm thinking that the second one could be more in tone.

I'm sure that @epowell101 and @sarob know more about the future "tone" of the logo and if it should be aligned with Gitcoins branding

**Comment by krrsna37** [comment]
> 
Thanks for correcting me, its actually a "community" rather a protocol. Below I have tried to present new design and feel.
(i)
![opendatacommunity](https://user-images.githubusercontent.com/81230749/218297063-41dc0748-2d85-42ca-a9b4-d56564f1cf2d.jpeg)
(ii).
![Opendatacommunity2](https://user-images.githubusercontent.com/81230749/218297074-7d376fb0-9649-48c2-8a2e-010cb524aea4.jpeg)

**Comment by krrsna37** [comment]
And also this one

![Opendatacomm3](https://user-images.githubusercontent.com/81230749/218297391-bc45dd26-e2c0-4325-8a89-7cf309b51482.jpeg)

**Comment by sarob** [comment]
I prefer 2 with logo design and light, dark green. The logo equal size the initials as [logo] ODC for wide icons and letterhead would look good.

**Comment by krrsna37** [comment]
Thank you so much for your kind comment.

**Comment by poupou-web3** [comment]
I like (i) Because it also shows the idea of community and coordination but I don't thing the small lines from the "circle" will be distinguishable on a small icon. For the (ii) I agree with the previous comment.

**Comment by kanayo-uzo** [comment]
Hey guys, I'm a Logo and Brand Designer. I'd love to contribute to the community.

**Comment by hebb00** [comment]
![Screenshot_20230509_152553](https://github.com/OpenDataforWeb3/Resources/assets/62152160/8
![Screenshot_20230509_152649](https://github.com/OpenDataforWeb3/Resources/assets/62152160/ff3fa2dd-3003-445e-b68d-e9f895d12345)

**Comment by hebb00** [comment]
![Screenshot_20230509_152510](https://github.com/OpenDataforWeb3/Resources/assets/62152160/dc052a91-d51d-43bf-baca-c32559062f97)

**Comment by hebb00** [comment]
i like this one :)
![Screenshot_20230509_152414](https://github.com/OpenDataforWeb3/Resources/assets/62152160/f84c345a-4d66-429c-b28b-572cdff51628)

**Comment by sarob** [comment]
I like the last one !

**Comment by Abuchtela** [comment]
I’ve got quite a few I created myself…… if you would like
