### ISSUE TITLE
Write up intro to next hackathon(s)

### ISSUE THREAD

**Issue by epowell101** [OpenDataforWeb3/Resources#133]
Items to cover may include:

Intro:
- 3rd hackathon
- Community governed
- wtf ODC?

Structure:
- Grants
- Sybils
- Decentralized data (POKT for eg)

Duration:
- The grants round ++ a bit IMO?

Next step:
- We need 2-3 sponsors, should get in touch immediately
- July, October likely additional hackathons (confirm vs. Gitcoin rounds)

**Comment by Razga** [comment]
I can write it, but will probly need some support 🗡️

**Comment by epowell101** [comment]
Done and published - we now just need additional sponsors to further specify.
