### ISSUE TITLE
Document the Regen Rangers pipeline and related governance

### ISSUE THREAD

**Issue by epowell101** [OpenDataforWeb3/Resources#136]
Drawing of the stages

Use of Soul Bound Tokens

**Comment by sarob** [comment]
see https://github.com/OpenDataforWeb3/governance/pull/6 and https://forum.opendatacommunity.org/t/people-pipelines-or-how-to-become-a-regen-ranger-and-an-odc-jedi/16

**Comment by epowell101** [comment]
published version onto Discourse.  Closed (for now)
