### ISSUE TITLE
Create a Lego registry - Sandbox?

### ISSUE THREAD

**Issue by epowell101** [OpenDataforWeb3/Resources#138]
How can we track all of the Legos?

Should we put them into a single repository or different ones?

Would it be in the Sandbox?  

Also should we fork and include the Lego Documentation?
- [https://github.com/Fraud-Detection-and-Defense/lego-docs#lego-ideas](https://github.com/Fraud-Detection-and-Defense/lego-docs#lego-ideas)

Perhaps we could have a readme or similar that indexes all of them.  

From one interested consumer of this information:

"cool.. yeah a "Lego registry / Index" that lists the legos by status (hypothesis, latest experiment results, which are in ideation, etc) would help me grok it"

**Comment by poupou-web3** [comment]
I expect to be able to access the lego both from the website and from Github. Each lego should have a title and short description on the website. On Github, we could also include the name of the project referent and other status such as the ones you proposed.

**Comment by stefi-says** [comment]
I feel this could be a project that the community can own inside the Sandbox , the Lego project could be alive , with clear guidelines for who ever wants to build one of the ' to be build legos"  just build it , submit a PR and add it to maybe " the ODC Legos Python Package"  ( dreaming out loud) . Will talk about this with people on today's Sandbox meeting. @epowell101

**Comment by epowell101** [comment]
I have made some progress here this weekend.

1.  Went into our version of the Lego docus and updated them for accuracy and readability.  
for example:  https://github.com/OpenDataforWeb3/Resources/blob/main/docs/Legos.md

2.  Started to trial of MarkPrompt
- evaluating to determine whether to add to our landing page; right now looks fairly useful - next step is to try to use chatGPT-4 with it to address some annoying errors

If we execute on these two pieces continuously - 
- improve underlying docs - to include interesting Legos
- continue to train the AI 

I think we will have addressed this use case.

**Comment by sarob** [comment]
forked to https://github.com/OpenDataforWeb3-sandbox/Lego-Curation/issues/new
