### ISSUE TITLE
legal structure for community

### ISSUE THREAD

**Issue by epowell101** [OpenDataforWeb3/Resources#14]
Should we create a non-US foundation?   We can ask a few useful lawyers and see what they say.

**Comment by Kishoraditya** [comment]
Until then just to keep the work in check we can work with open source licenses 
I like creative commons, GNU v3 and DCO signatures in open source projects

**Comment by sarob** [comment]
I'd start with someone like Radcliffe at DLA Piper on retainer while looking for 1-2 others that have commercial interests and will donate their time.

**Comment by epowell101** [comment]
Yes, agreed.  FWIW we are meeting w/ some of the options in the days to come.

**Comment by sarob** [comment]
Makes sense. Thanks for the update!

**Comment by epowell101** [comment]
Acting as a UNA for now.  May want additional structures as we grow.
