### ISSUE TITLE
Add Forum to the home page of the website

### ISSUE THREAD

**Issue by epowell101** [OpenDataforWeb3/Resources#144]
Let's figure out what to call it - whatever people think

And add it to the navigation

[https://forum.opendatacommunity.org/](https://forum.opendatacommunity.org/)

**Comment by sarob** [comment]
I want to make it more specific like proposal.opendatacommunity

**Comment by sarob** [comment]
this is a good issue for hebbs00 to add to the website

**Comment by SpaceTristan** [comment]
> @baokiddy this is a good issue for hebbs00 to add to the website

Will we want this just to be a simple link to the Discourse page? Something added say to the top menu bar as a button?

**Comment by sarob** [comment]
> > @baokiddy this is a good issue for hebbs00 to add to the website
> 
> Will we want this just to be a simple link to the Discourse page? Something added say to the top menu bar as a button?

I think Proposals as the menu text
