### ISSUE TITLE
update hackathon menu

### ISSUE THREAD

**Issue by sarob** [OpenDataforWeb3/Resources#145]
I think it should to point to the hackathon repository which references all of the past and soon future events. Another task for hebbs?

**Comment by hebb00** [comment]
what about we make the hackathon menu item take to a page that shows information about the current running hackathon or the upcoming one and then show information about previous hackathons and links to resources.

**Comment by sarob** [comment]
> what about we make the hackathon menu item take to a page that shows information about the current running hackathon or the upcoming one and then show information about previous hackathons and links to resources.

Sounds good, you can use the hackathon README and two markdown pages we can remove the hackathon repo as redundant.

**Comment by sarob** [comment]
Any update on this?

**Comment by hebb00** [comment]
![Uploading image.png…]()

**Comment by hebb00** [comment]
![image](https://user-images.githubusercontent.com/62152160/228314305-7a4a7ee6-0523-41e2-8b89-3811ea22d4a9.png)

**Comment by hebb00** [comment]
![Uploading 98C45D7F-A7A5-48A7-951D-760E9A207E5D.png…]()

**Comment by hebb00** [comment]
![F9FAF82B-EFE0-418D-8D79-61B99777D7FE](https://user-images.githubusercontent.com/62152160/228388166-88fac950-f40a-466b-bf37-0511381d2fd0.png)

**Comment by hebb00** [comment]
![hackathon](https://user-images.githubusercontent.com/62152160/228394018-3d6d04f5-8e79-4f0f-b06d-aaf401da3693.png)
