### ISSUE TITLE
evaluate alternative hackathon platforms

### ISSUE THREAD

**Issue by epowell101** [OpenDataforWeb3/Resources#148]
Alternatives include:

- https://desights.ai/  Ocean
- https://taikai.network/organizations  EthSamba

Criteria might include:
- ease of use for contestants
- ease of use for administrator
   - click to pay for example
- traffic - would help bring other contestants in
- other basic features:
    - adding content

**Comment by epowell101** [comment]
I started on this - scheduling demos.

I think we s/d commit to Buildbox due to overall alignment.  That said so far the Takai.network looks at least at the marketing level to be very interesting.

**Comment by epowell101** [comment]
Here is the working spreadsheet - very rough however it does implement the basics of:
- criteria
- alternatives
- evaluation

[evaluation spreadsheet](https://docs.google.com/spreadsheets/d/11Yf-H7sDndRowqLTMjT5ukkJxdj5Yt5550nLWVNlc7Y/edit#gid=0)

**Comment by sarob** [comment]
I think we have decided on buldibox, so should we close this?

**Comment by sarob** [comment]
closing as it appears we have decided to use buldibox. reopen if in error.
