### ISSUE TITLE
stand up an Ethereum node on Akash

### ISSUE THREAD

**Issue by epowell101** [OpenDataforWeb3/Resources#149]
Let's set up a Eth node running on Akash

1.  Per this documentation, go to their Discord and request some tokens - please establish or use an account that ODC can take over funding of in the future

- https://docs.akash.network/tokens-and-wallets/funding
(it appears they no longer have a faucet)

2.  As an Eth node we will use Erigon
https://github.com/ledgerwatch/erigon 

3.  We may be able to run a containerized version of Erigon in this way:
https://hub.docker.com/r/thorax/erigon

4. Here is a dated blog on running a containerized application on Akash:
https://medium.com/coinmonks/guide-to-deploying-applications-to-akash-decloud-b35dc97e5ca4

5.  Notify ODC via the eng-general channel on the ODC Discord
- we will DM you to communicate further

**Comment by epowell101** [comment]
The process to get credits on Akash is to drop into their discord and ask them for credits.  FWIW a few folks there at least know who the OpenData Community is.

**Comment by sarob** [comment]
and this trueblocks-erigon channel is the main source of truth I think https://discord.com/channels/570963863428661248/934811153899597855

**Comment by sarob** [comment]
Rene Aavik has been working on the Gitcoin grant that would complete this issue. We can see some of his conversation and work completed so here https://discord.com/channels/747885925232672829/771909909335506955/1091059277868830751 on the Akash discord. 

Where do we want the results of his work on getting an Erigon node working on Akash and the infrastructure pricing of the AKT tokens to be documented?

**Comment by epowell101** [comment]
I opened a new issue on that above subject - I am not sure where to put it.

For now I've forked it into my repository:  https://gist.github.com/epowell101/6aef4c3b1252922cfba4e563dd6d6ecd

**Comment by sarob** [comment]
Work was completed and gist copied into the ops directory
