### ISSUE TITLE
engineering to make migration FDD.io to ODC happen

### ISSUE THREAD

**Issue by sarob** [OpenDataforWeb3/Resources#158]
@zen is our gitcoin FDD contact on this

**Comment by zen** [comment]
No, I'm not ;)

**Comment by sarob** [comment]
from https://discord.com/channels/1037443230993743902/1068197163353505916/1100247806964404274

Not as urgent as the possible face lift to the web site - but @ZEN mentioned they are ready to move to ODC the fddhub.io web site.

We were thinking we put it at data.opendatacommunity.org - which is easy enough.

I have not thought through the hosting though.  Maybe Zen or others have some thoughts about that.   Are we able to move over the data and the simple UI or should we build a simple Hugo page?

We could also use that URL for some of the data that is in the FAQ @baoki | Gitcoin FDD & ODC just published as well.

I guess on the whole I'm feeling maybe it makes sense to design a simple site that incorporates current and future datasets.

**Comment by epowell101** [comment]
I believe this is done.  Thank you @zengatsu !
