### ISSUE TITLE
Take live a reactive front page to our web site

### ISSUE THREAD

**Issue by epowell101** [OpenDataforWeb3/Resources#170]
As mentioned in Discord, we have developed a more interactive front page:
https://opendatacommunity.org/web_test/

We now need this content to replace the content as specifically opendatacommunity.org

The sub domains such as forum, opendatacommunity.org would not change.

Similarly we would also not change URLs such as:  https://opendatacommunity.org/about-us/

**Comment by sarob** [comment]
seems like this is the solution https://gohugo.io/templates/homepage/

looking into it

**Comment by SpaceTristan** [comment]
> @SpaceTristan so should we simply replace the Hugo site index.html content with 
> <meta http-equiv="refresh" content="0"; URL="https://opendatacommunity.org/home/" />  until we can convert over to react based site or 
> or is there a way to merge the two?
> 

Yeah I think that will work. I will able to be more engaged this week with things so we can maybe do a call on this but it should be that simple. Is opendatacommunit.org being hosted from pages right now?

**Comment by sarob** [comment]
@SpaceTristan evan was have problems with a https redirect I think. I’ll look into creating a PR for moving the hugo site content into the new site and managing going forward with vsc react extension.

**Comment by SpaceTristan** [comment]
> @SpaceTristan evan was have problems with a https redirect I think. I’ll look into creating a PR for moving the hugo site content into the new site and managing going forward with vsc react extension.

Sounds good. Lets talk more about this in tomorrow's engineering meeting. I didn't realize the new site was pointing back to the hugo site for things

**Comment by sarob** [comment]
@hebb00 somewhere between yesterday and today's updates, your test deployment at https://hebb00.github.io/odc/ looks to be have the layout broken.

The most recent render here https://github.com/hebb00/odc/actions/runs/4797829989

PR at https://github.com/OpenDataforWeb3/opendataforweb3.github.io/pull/37

**Comment by sarob** [comment]
PR merged and site is live. great work @hebb00 !
