### ISSUE TITLE
Writer's guild

### ISSUE THREAD

**Issue by sarob** [OpenDataforWeb3/Resources#23]
### On 28Nov2022, zer8 wrote Maybe we could even start a writers guild. We could use crew3 to start.What do you think @epowell101 ? https://discord.com/channels/1037443230993743902/1037443231438360722/1046955409031831632
- A quests platform: http://crew3.xyz/  It's cool because you acumulate XP which can later mean smth in the context of a community.
- We can prioritize research during the weekly meetings
- we should write a research getting started page similar to:

Support the ODC mission by researching the decentralization landscape 

Setting up local workstation for writing research , e.g. download Visual Studio Code, add markdown extension, download GitHub desktop to manage changes, through GitHub desktop clone https://github.com/OpenDataforWeb3/Landscape.wiki.git, blah blah

Other stuff for a researcher to think about ...

**Comment by SpaceTristan** [comment]
What do you think about maybe after we get some research and papers together, we could put together articles and post onto Medium? I use it regularly for reading articles and I definitely find out about a lot of projects and communities through there.

**Comment by sarob** [comment]
> What do you think about maybe after we get some research and papers together, we could put together articles and post onto Medium? I use it regularly for reading articles and I definitely find out about a lot of projects and communities through there.

I like the idea of publishing to medium as our blog. I'll mention on the ops design channel.

**Comment by sarob** [comment]
> Hey @sarob thanks for pasting this here. Yes, crew3 is great and we should try to use it to form the ODC. Every task can be nicely defined and tracked, not actually a fan of the long term outcomes that it leads 2 but it could be a start.

Awesome, sounds like you have some experience with crew3. Can we link crew3 tasks with github issues and projects? I'm thinking so non-crew3 users could still participate on work and GitHub profile stats represent all contributions.

**Comment by sarob** [comment]
Similar to your other idea of pairing up to get work done @Razga this is an option. I think we should add this to the review of github project and dework.

**Comment by sarob** [comment]
This seems to be a duplicate of other issues. I'll close this one for now.
