### ISSUE TITLE
Hackathon: prepare for Jan 2023 Hackathon - tasks

### ISSUE THREAD

**Issue by epowell101** [OpenDataforWeb3/Resources#25]
- more feedback on write up:  https://docs.google.com/document/d/1TlU3dpe7z1IfYLgs7VGYIqPkpSfNRacMIGtLw1sh70U/edit#heading=h.2l21l9phc1jo
- FAQ +:  project kicked off
- Twitter spaces for promotion
- Sponsors
- Implement site:  connect to Gitcoin hackathon team (again) -> update -> we should research alternatives asap as well
    [](https://gitcoin.co/hackathon/DataBuilders/onboard)
- Data preparation:  data from Unicef & Fantom rounds to be prepared by FDD Gitcoin
- Explanation of data:  what are the columns?
- Specifics on bounties:  (see write up)
- Implementation of bounties:  (Github issues either in this or FDD Github)
    - create issues https://gitcoin.co/bounty/new

**Comment by baokiddy** [comment]
Work on FAQ/guides for the Hackathon can be found [here](https://github.com/OpenDataforWeb3/Landscape/issues/24)

**Comment by epowell101** [comment]
Landing page for hackathon is:
https://gitcoin.co/hackathon/DataBuilders/onboard

**Comment by sarob** [comment]
verification that the above tasks have either been completed or turned into issues

- DONE FAQ +: project kicked off
- DONE Twitter spaces for promotion
- DONE Sponsors

@epowell101 Below completed or which need to be assigned as issues?
- Implement site: connect to Gitcoin hackathon team (again) -> update -> we should research alternatives asap as well
- Data preparation: data from Unicef & Fantom rounds to be prepared by FDD Gitcoin
- Explanation of data: what are the columns?
- Specifics on bounties: (see write up)
- Implementation of bounties: (Github issues either in this or FDD Github)
- create issues https://gitcoin.co/bounty/new
- data builder hackathon marketing plan https://docs.google.com/document/d/1TlU3dpe7z1IfYLgs7VGYIqPkpSfNRacMIGtLw1sh70U/edit?usp=sharing
- data builders hackathon messaging plan https://docs.google.com/document/d/1hQL81C6LJqCbUAVjDisU-Mx6TOD1_rKqz6FRBgFGjKE/edit?usp=sharing

**Comment by epowell101** [comment]
We are not done on much of the marketing
We have not revised the landing page with updated information
We need to implement the bounties
We could pull items out from the marketing plan and elsewhere and put them here however until we do that we are stcuik with this aggregate issue.  Please do not close it @sarob

**Comment by sarob** [comment]
Roger @epowell101 , slowly backing away

**Comment by epowell101** [comment]
I think we can close this - in part to focus on incremental improvements
