### ISSUE TITLE
Explaining in short terms zksync and bulk transaction for the FAQ- What is ? How does it works?

### ISSUE THREAD

**Issue by stefi-says** [OpenDataforWeb3/Resources#40]
We would like some help to anwers a question for our FAQ: 

What is zksync? How is related to bulk transaction? How does it works? 

the intent here is to help newcomers to understand this issue and make better analysis on sybil attacks, some media for further research would be apreciated , youtube videos, podcasts and so on

**Comment by Abuchtela** [comment]
ZKSync is a Layer 2 blockchain scaling technology that allows for batching of transactions which enables high transaction throughput and low transaction fees. It works by using off-chain channels to bundle multiple transactions into a single transaction, which is then sent to the blockchain – meaning only a single on-chain transaction is required for a given set of operations. This significantly reduces the cost, complexity and time needed to execute a large number of transactions.

**Comment by Abuchtela** [comment]
@Abuchtela
