### ISSUE TITLE
Tools to improve ODC collaboration

### ISSUE THREAD

**Issue by sarob** [OpenDataforWeb3/Resources#45]
1. **Buildbox** Anyone want to participate in selecting a hackathon platform for FUTURE (post January) hackathons?  I think it is probably the case that the new Gitcoin (actually now Supermodular) platform called https://buidlbox.io/ will be the winner however perhaps ironically given that we were founded by Gitcoin I think it'd be good to do some public research on the alternatives & take demos from them and others & otherwise be as transparent as possible.  Of course Supermodular are also a hackathon sponsor - but they are charging us as well.  Anyway - could be a piece of research that others pick up on including non web3.  cc <@234051561649733632> just because great research in the past however open to all.  Not urgent, but should be done relatively soon (first half of January?) & we can include it in the potential ODC bounties from hackathon **posted from msg https://discord.com/channels/1037443230993743902/1038206685224902658/1055197508185366539**
2. **Crew3** A quests platform: http://crew3.xyz/  It's cool because you acumulate XP which can later mean smth in the context of a community. **Posted from msg https://discord.com/channels/1037443230993743902/1037443231438360722/1047238864508571699**
3. **autonolas** hey friend, alot has happened in this discord, beautiful to see. I'd like to propose implementing something like this to track contributions. https://contribute.autonolas.network/docs#section-actions **posted from msg https://discord.com/channels/1037443230993743902/1038206685224902658/1055230936016506990**
4. **OpenDev** Regarding bounties and more -> I am just learning a little bit about https://www.openq.dev/ it is more like for ongoing enablement & paying bounties.  The idea of a permanent hackathon has been discussed 🤔<a:thinkspin:905468634556665926> **posted from msg https://discord.com/channels/1037443230993743902/1038206685224902658/1055271496416768081**
5. **Govrn**
6. **Orbit**
7. **Lenster**
8. **DeWork** It looks nice to aggregate everything in one place. Do you think the starter pack would be enough? I think Dework could also be an good solution for task management. It offers kamban project management that automatically integrates with GitHub and does many other things
https://dework.xyz/ **posted from msg https://discord.com/channels/1037443230993743902/1038206685224902658/1052603999385292881**
9. **Discord**
10. **Twitter**
11. **Orb**
12. **1p1v** **posted from msg https://discord.com/channels/1037443230993743902/1038206685224902658/1056868460463915088**

**Comment by sarob** [comment]
This is great!  Thank you.  Part of what makes my brain hurt a bit is we have a few related “requirements” - and maybe solidifying these is the first step; as I see it these requirements include:
1. Organize ourselves - 
- limit duplicate work (check out?)
- enable permissionless addition of tasks / like issues 
- give a backlog like view
2.  Document contributions for any future bounties & membership in technical house via SBTs
3.  Analysis for use by devrel team to focus efforts & reporting to sponsors and the broader community
- note - if we are on chain - a dashboard like Dune or any other more decentralized approach could work; we cd even build our own; however discord & Twitter & Github obviously not on chain so…
4.  Distribution of SBTs or similar (SAFE is using non transferable erc 20s)  - might export from an orbit or dework for a whitelist for eg
5.  Voting - actually doing voting - snapshot perhaps and then use tally for on chain or?  For hackathons we want to use QV - and eventually the grants protocol from gitcoin may enable - or Factory DAO or other

Sorry the above is a bit rough.  Using thumbs to write 😅👍

**Posted from msg https://discord.com/channels/1037443230993743902/1038206685224902658/1056279117013721201**

**Comment by sarob** [comment]
From @curiousrabbit-eth 
i would say right now no. It also demands development from someone with python skills in our community, and there is a cost associated with running our own Autonomous Service that keeps track of the data and sends the updates onchain. 

Govern seems pretty straight forward and its integrated with the discord

Personally though i am bias to Autonolas because of the unlock i think it will enable as the protocol gains traction. 

I can see the ODC developing useful Autonomous Services using Autonolas that end up becoming revenue generating opportunities. I also see it as a bridge between Web2 and Web3, but one that enables decentralized and complex services to be linked on and off chain.

Anyways im just rly into it at the moment, which is why i want the ODC to get into it.... im completely bias.

Govrn seems like a faster and easier solution to implement, albeit it does not enable new doors to open as autonolas does

**Comment by sarob** [comment]
https://twitter.com/andrewhong5297/status/1611392835898449920

![A629587F-47DD-4E07-B3C4-7EB147FBE6D9](https://user-images.githubusercontent.com/1191994/211435925-7fee88d4-cd57-4c5c-87d6-79a013432d23.jpeg)

**Comment by sarob** [comment]
I have configured dework with a space for the ODC. Integration with GitHub and discord. We should be able to configure Gnosis as well, but ideally on something similar to a feature rather than a story or issue. You can explore the site here https://app.dework.xyz/opendata-community. ODC Jedi have configuration rights, so tread softly until we figure out the best way to fine tune the setup.

**Comment by sarob** [comment]
I haven't seen anyone take advantage of dework, it seems that it likely isn't a good tool for us. I'll keep looking.

**Comment by epowell101** [comment]
We do have a Utopia account that we have for free - I think including gas fees.

**Comment by sarob** [comment]
Closing for now
