### ISSUE TITLE
Author a FAQ that could help another community member and hackathon participant

### ISSUE THREAD

**Issue by epowell101** [OpenDataforWeb3/Resources#65]
There are several FAQs that have been authored.

What other FAQs should be listed?  Please take a crack at authoring a new FAQ by making a pull request against the FAQ file:
[https://github.com/OpenDataforWeb3/Resources/blob/main/docs/faq.md](https://github.com/OpenDataforWeb3/Resources/blob/main/docs/faq.md)

Please do NOT close this issue.  This can be an ever green / ever open issue - much like the issue about adding projects to Landscape.

**Comment by owanikin** [comment]
Hello @epowell101 I'll love to take this on. Kindly assign it to me.

**Comment by epowell101** [comment]
Hi @owanikin - what we will do is add you to the organization.  This will allow you to make a Pull Request against the FAQ file:
[](https://github.com/OpenDataforWeb3/Resources/blob/main/docs/faq.md)

**Comment by owanikin** [comment]
Okay thanks @epowell101 looking forward to you adding me to the organization.

**Comment by epowell101** [comment]
Hey @owanikin you should have been added the other day - can you check it out and see if you can open a PR for example?

Also - WELCOME!  This is how we do it :)

**Comment by nwakaku** [comment]
Hello @epowell101  can I be assigned this too I will like to take on this

**Comment by epowell101** [comment]
Closing for now.  Presumably we will have something like this in the upcoming hackathon as well and we can reopen or create a new one at that time.
