### ISSUE TITLE
Spaces to podcasts

### ISSUE THREAD

**Issue by sarob** [OpenDataforWeb3/Resources#66]
The twitter spaces recordings are available for 30 days via twitter so we need a way to make them available for longer. 

I took the time to run a podcast last year for a startup, so I have some recent experience of what we can do to make these recordings available longer and probably increase their reach. 

Using macOS iMovie, we can typically publish back to Twitter, Linkedin, YouTube, Facebook and SimpleCast (Spotify, Apple, and Overcast). Simplecast costs $15/month to push casts to multiple platforms. I can share how I created a jingle, header, footer, cropped recordings, and published. It took about an 1-2 hours each week to do the work including doing the interviews. If we do this as a team, a cast can be published with little effort. 

We can start simple, just copying from one place to another. As the reach grows, the audience expectations of a professional polish become higher.

**Comment by epowell101** [comment]
Someone mentioned Airmeet as a podcast platform

**Comment by sarob** [comment]
Airmeet appears to be a an event management company with some tooling.

**Comment by stefi-says** [comment]
Hey guys! @epowell101 have we already downloaded the twitter spaces ? Im afraid we could lose them... 
I will do some research to figured out if we can publish it using lens. 
I can help out gathering and updating  them in a blogpost in our website. Maybe writing title and summaries to enhance engagement:)

**Comment by sarob** [comment]
@epowell101 , @stefi-says , @baokiddy  are interested so I wrote more details here https://github.com/OpenDataforWeb3/Resources/wiki/Streams-to-Podcasts

**Comment by sarob** [comment]
Going to close this as it is moving forward.  I'll create a PR to add the cast ops workflow.
