### ISSUE TITLE
Create GitHub action supporting website to commit file changes

### ISSUE THREAD

**Issue by sarob** [OpenDataforWeb3/Resources#67]

**Comment by sarob** [comment]
I generally like this approach of single place for CICD work while we are using actions. https://github.com/protocol/.github

**Comment by sarob** [comment]
three options for the website/marketing team:
1. Update docs, blog, image content with multiple PRs in the default dev branch on the resources repository over a few days. Once ready to publish, merge the dev branch with the main branch.
2. OR there is a duplicate website structure in ODC/resources/website/ directory that can be updated with PRs.
3. OR dev branch in the opendataforweb3.github.io repo that is updated with PRs. 

for all above:

A GitHub action will update the dev website with the content. Website required metadata headers get created by the action using GitHub data like contributor, date time, and title. A 5 minute timer will start and once finished the public website will get updated. The timer can be stopped and the public website can be updated from the dev website manually.

I prefer option 1 as it would be the easiest for new contributors to understand.

**Comment by SpaceTristan** [comment]
> three options for the website/marketing team:
> 1. Update docs, blog, image content with multiple PRs in the default dev branch on the resources repository over a few days. Once ready to publish, merge the dev branch with the main branch.
> 2. OR there is a duplicate website structure in ODC/resources/website/ directory that can be updated with PRs.
> 3. OR dev branch in the opendataforweb3.github.io repo that is updated with PRs. 
> 
> for all above:
> 
> A GitHub action will update the dev website with the content. Website required metadata headers get created by the action using GitHub data like contributor, date time, and title. A 5 minute timer will start and once finished the public website will get updated. The timer can be stopped and the public website can be updated from the dev website manually.
> 
> I prefer option 1 as it would be the easiest for new contributors to understand. 

I agree that option 1 would be the easiest path to go with this

**Comment by sarob** [comment]
@SpaceTristan I started looking through example actions and came across one using label on merge. I’m thinking asking the people creating PRs to simply add the Publish label and then on PR merge with the Publish label the action commits the files to main on the website repo which causes the publish action there. I’ll add the metadata headers to the resource files. 

We can add the dev site and dev to main branch merging as we have more time and maybe people to help.  Sound like a plan?

**Comment by sarob** [comment]
still needs some work. maybe we can finish this weekend :)

**Comment by sarob** [comment]
We are still working on it

**Comment by Rnamita** [comment]
I would be interested to contribute here, just a suggestion - can we use GitHub pages - a branch such as GitHub pages so when the changes are pushed to gh-pages from master it is published. I also see Jekyll being used in pages build and deployment workflow - https://github.com/OpenDataforWeb3/Resources/actions/runs/3824953097 is it in integration with GitHub pages

**Comment by SpaceTristan** [comment]
> @sarob @SpaceTristan I would be interested to contribute here, just a suggestion - can we use GitHub pages - a branch such as GitHub pages so when the changes are pushed to gh-pages from master it is published. I also see Jekyll being used in pages build and deployment workflow - https://github.com/OpenDataforWeb3/Resources/actions/runs/3824953097 is it in integration with GitHub pages 

So we already are using GitHub pages. You can find the website on this [repo](https://github.com/OpenDataforWeb3/opendataforweb3.github.io) 

We aren't using Jekyll but instead Hugo with the Doks template. To find more details on Hugo check [here](https://gohugo.io/documentation/) and for docs, [this](https://getdoks.org/) is a useful starting place.

**Comment by sarob** [comment]
Closing for now
