### ISSUE TITLE
Prepare grant and partner discussion materials

### ISSUE THREAD

**Issue by epowell101** [OpenDataforWeb3/Resources#73]
Before the end of the hackathon we should be kicking off conversations with our partners & possible grant providers - like Aave.

This work includes:
- discussing internally our 12 month plan
- modeling that with a reasonable budget that includes bounties and a number of hackathons (quarterly?)
- describing the benefits to grants and founding partners; quantifying benefits from the hackathons & getting quotes from participants and sponsors
- from that modeling how many supporters and grant providers of what size we need
- creating a list of 30+ partners for outreach - and starting to request introductions and similar
- potentially dividing the work up when it comes to grant prep and meeting prep 
- FDD from Gitcoin will be the first group that we pitch on our value
- using DAO Denver as an opportunity to meet in person & potentially close a set of founding supporters
- calculating a simple issuance model for founding supporters and for the community based on the assumption that we will have something like a bicameral structure similar to the Cloud Native Computing Foundation and Optimism - whereby technical & community decisions are made on their merits AND an oversight function from sponsors and supporters to ensure wise use of funds

**Comment by curiousrabbit-eth** [comment]
can we start to add ideas here? https://auspicious-cap-b5c.notion.site/Grant-Partner-Materials-a1294033dd1b449e88a9eff65c6d82da

**Comment by sarob** [comment]
I can’t get notion to let me edit on iOS, so my bits here
 
Conference: ethDenver is good opportunity to build some momentum with projects as well as with sponsors. Planning a milestone for the next hackathon events and or project(s) release. 

governance model: 
- board of directors or governing board: With either name it needs to be a combination of sponsors and the community. The community representation needs to be voted in.   
- administration staff: they will need to be managed by a paid leader. That leader will need to be managed the BoD / governance board. 
- Technical Committee: Project leaders to start. Add a few voted in community members later. 
- Projects: allow them to self organize using the tools. When they are ready, a leader is voted in.

**Comment by epowell101** [comment]
This is ongoing - and for example I'll be incorporating the people and project pipelines as well as the Regen Rangers into the deck.  However I think we can close it for now as we have something >1.0
