### ISSUE TITLE
Create a reference list of useful Legos

### ISSUE THREAD

**Issue by epowell101** [OpenDataforWeb3/Resources#80]
The project is to create a list of Legos via a file similar to the OpenData Community [Landscape](https://opendatacommunity.org/docs/landscape/)
Some tasks would include:
- create the file in the DOCS folder:  [DOCS FOLDER](https://github.com/OpenDataforWeb3/Resources/tree/main/docs)
- establish a standard format similar to:
    - [LEGO NAME]
    - [EXPLANATION]
    - [URL]
    - [OTHER]
 - Add at least 3 example Legos
 
 For example - for Grants review one was shared via this Twitter thread:
 - [Carl C introduction of how he is scoring Grants](https://twitter.com/carl_cervone/status/1616792961412640772?s=20&t=oM-q7bjECgrHcUL1848fkg)

**Comment by poupou-web3** [comment]
One very useful link : https://github.com/Fraud-Detection-and-Defense/lego-docs

**Comment by epowell101** [comment]
Yes - here is another (posted on Discord by DisruptionJoe from Gitcoin FDD):
- [Spreadsheet](https://docs.google.com/spreadsheets/d/1sMgm3cg3pfMvRbmrteknpu44qsyuQlvn3vizgwnOgOU/edit?usp=sharing)
