### ISSUE TITLE
Design logo

### ISSUE THREAD

**Issue by epowell101** [OpenDataforWeb3/Resources#9]
Asked Gitcoin MMM for help Monday 10/31 - no response as of end of day.  Will follow up

**Comment by SpaceTristan** [comment]
Not sure if you are still looking to do more with this but I found a fun logo making tool to experiment more with here: 

https://www.namecheap.com/logo-maker/app/

Here are a few I made with it:

![image](https://user-images.githubusercontent.com/29065567/206628631-9fbdbb35-3e6d-4792-956b-3527400f2b42.png)
![image](https://user-images.githubusercontent.com/29065567/206628801-6bee2021-8522-4395-aa97-6a40904870e5.png)
![image](https://user-images.githubusercontent.com/29065567/206628941-e1a7654c-df59-49cc-a658-aaa7b1c62dac.png)

**Comment by epowell101** [comment]
We are going w/ the current logo for this hackathon - it has already been sent around and built into materials.  We can do a contest or similar in the future for a new one.

**Comment by sarob** [comment]
Duplicate of #120
